CertainLach/jrsonnet

crates/jrsonnet-evaluator/src/builtin/mod.rs, crates/jrsonnet-evaluator/src/error.rs, crates/jrsonnet-evaluator/src/evaluate.rs, crates/jrsonnet-evaluator/src/lib.rs, crates/jrsonnet-evaluator/src/val.rs, crates/jrsonnet-parser/src/expr.rs, crates/jrsonnet-parser/src/lib.rs
Also removes intrinsic interface for natives, they weren't useable for users
anyway, and we have native callback support now.
Fixes https://github.com/google/jsonnet/issues/378
Fixes https://github.com/google/go-jsonnet/issues/69
=> Prevent changing meaning of std in desugared expressions

.github/workflows/release.yml
I'm creating the [`kct`](https://github.com/kseat/kct) CLI, which is very dependent on this project; consequently, I've been watching your changes. Although unable to contribute due to my shallow Rust knowledge. On the other hand, I can help you with releasing your crates to crates.io. That also helps me because I'm keen to try out the 0.3.5 version, which unfortunately wasn't published yet.
For that, I used the [`cargo-release`](https://github.com/sunng87/cargo-release) while disabling all the git functionality so you can have complete control over your release process. I've tested this on [`kct`](https://github.com/kseat/kct/runs/2472200698?check_suite_focus=true#step:7:26) to be sure that everything would work, and it did, despite the build failure. The only problem is if the process …
=> Add job to publish to crates.io

.github/workflows/release.yml
While implementing the build for all tier-1 platforms, I misconfigured the ARM build and didn't test it thoroughly. The changes fix the missing `build` command for `cross` and set the correct `strip` command for ARM builds. You can check that it's working correctly [here](https://github.com/bruno-delfino1995/jrsonnet/actions/runs/893853315).
=> build: fix strip and build for ARM

.github/workflows/release.yml, Cargo.lock, README.md, cmds/jrsonnet/Cargo.toml, crates/jrsonnet-cli/Cargo.toml, crates/jrsonnet-interner/.gitignore, crates/jrsonnet-stdlib/Cargo.toml
When trying to build non-x64 binaries, my first attempt was to leverage the Rust Ecosystem. However, that was impossible because of a git dependency, as noted [here](https://github.com/CertainLach/jrsonnet/issues/35#issuecomment-844436711) by @CertainLach. I managed to build the binaries using cross compilers, but the workflows turned out quite ugly. Instead of committing to this workflow, I chose to change from the git ref to the prerelease of clap-rs.
Since using either ref or prerelease gives us the same API stability, I thought you wouldn't consider this to be a problem. Now we can publish the package to crates.io and leverage the Rust Ecosystem for all the non-x64 architectures.
Related-to: #35
=> Use clap prerelease instead of git ref

Cargo.lock, bindings/jsonnet/Cargo.toml, bindings/jsonnet/src/import.rs, bindings/jsonnet/src/lib.rs, crates/jrsonnet-evaluator/src/lib.rs
So that users of `jrsonnet-evaluator` don't need to explicitly depends on `jrsonnet-interner` just for the `IStr` type.
=> Re-export `IStr` in jrsonnet-evaluator crate

crates/jrsonnet-parser/src/expr.rs, crates/jrsonnet-parser/src/lib.rs
This pull request adds location information to all sub-expressions. So `loc_expr_todo!` is no longer needed.
The added test case `{} { local x = 1, x: x } + {}` previously lacks location information at ObjExtend sub-expression even when `loc_data: true` is given.
I'd like to use jrsonnet-parser crate to detect unused variables in Jsonnet files. Location information is important in this use-case.
=> Add location info to all sub-expressions

crates/jrsonnet-cli/src/lib.rs, crates/jrsonnet-parser/src/lib.rs
To fix #65 use case.
I'll let more experienced Rust develop tackle the JSONNET_PATH env var use case ;)
=> Enable multi-occurences for --jpath + improve positional params error message

bindings/jsonnet/src/import.rs
https://github.com/rust-lang/rust/blob/1.57.0/RELEASES.md#libraries
=> Add explicit drop() to avoid warning since Rust 1.57.0

crates/jrsonnet-stdlib/src/std.jsonnet
It was added in jsonnet v0.18.0.
https://github.com/google/jsonnet/commit/4e67da2c015bb316158d3e52a47376b38a29a4ef
=> Import `std.get(o, f, default=null, inc_hidden=true)`

crates/jrsonnet-stdlib/src/lib.rs, crates/jrsonnet-stdlib/src/strings.rs
This adds intrinsics for numeric parsing.
=> feat: add intrinsics for numeric parsing

crates/jrsonnet-stdlib/src/std.jsonnet
This removes int parsing functions from `std.jsonnet`
as they were intrinsified in #89.
=> chore: remove int parsing functions from std.jsonnet

crates/jrsonnet-stdlib/src/lib.rs, crates/jrsonnet-stdlib/src/math.rs, crates/jrsonnet-stdlib/src/std.jsonnet
This adds builtins for the following functions:
- `abs`
- `sign`
- `max`
- `min`
- `clamp`
=> feat: implement builtins for trivial numeric functions

crates/jrsonnet-stdlib/src/types.rs
This changes the variable name in the identity-related `is_X` builtin functions to match the variable names in the [jsonnet standard library](https://github.com/google/jsonnet/blob/master/stdlib/std.jsonnet#L28,L33).
This mainly serves to integrate better with libraries such as [k8s-libsonnet](https://github.com/jsonnet-libs/k8s-libsonnet/).
=> Fix: Use variable names from jsonnet stdlib for is_x builtins

bindings/Makefile, bindings/README.md
I'm working with jrsonnet as a C lib and only managed to build it like this. 
Works great now! Also added instructions to cross-build on MacOS if someone wondered how
=> fix: `.so` build instructions out of date

crates/jrsonnet-cli/src/stdlib.rs
Allow base64 encoded values, and large JSON strings that include "=" characters in the body
I had no idea how to test this, so I built it and ran it within the scope of my work
First piece of Rust code I've ever written :)
Thank you for this project! 🫶
=> Allow '=' within the body of --tla-code

Cargo.lock, crates/jrsonnet-stdlib/Cargo.toml, crates/jrsonnet-stdlib/src/arrays.rs, crates/jrsonnet-stdlib/src/hash.rs, crates/jrsonnet-stdlib/src/lib.rs, crates/jrsonnet-stdlib/src/math.rs, crates/jrsonnet-stdlib/src/objects.rs, crates/jrsonnet-stdlib/src/operator.rs, crates/jrsonnet-stdlib/src/std.jsonnet, crates/jrsonnet-stdlib/src/strings.rs
Hey 👋
I've implemented missing std features which were listed in the #118
You can test new features with the following jsonnet snippet:
```
{
local test = ["a", "b", "a"],
local obj = {a: "1", b: "2", c:: "3"},
round1: std.round(1.0),
round2: std.round(1.2),
round3: std.round(1.5),
isEven1: std.isEven(1),
isEven2: std.isEven(2),
isOdd1: std.isOdd(1),
isOdd2: std.isOdd(2),
isInteger1: std.isInteger(1.0),
isInteger2: std.isInteger(1.1),
isDecimal1: std.isDecimal(1.0),
isDecimal2: std.isDecimal(1.1),
xnortt: std.xnor(true, true),
xnortf: std.xnor(true, false),
xnorff: std.xnor(false, false),
isEmpty1: std.isEmpty(""),
isEmpty2: std.isEmpty(" "),
isEmpty3: std.isEmpty("abc"),
equalsIgnoreCase1: std.equalsIgnoreCase("a", "ac"),
equalsIgnoreCase2: std.equalsIgnoreCase("a", "a"), …
```
=> feat: missing std features

Cargo.lock, crates/jrsonnet-stdlib/Cargo.toml, crates/jrsonnet-stdlib/src/arrays.rs, crates/jrsonnet-stdlib/src/hash.rs, crates/jrsonnet-stdlib/src/lib.rs, crates/jrsonnet-stdlib/src/math.rs, crates/jrsonnet-stdlib/src/objects.rs, crates/jrsonnet-stdlib/src/operator.rs, crates/jrsonnet-stdlib/src/sort.rs, crates/jrsonnet-stdlib/src/std.jsonnet, crates/jrsonnet-stdlib/src/strings.rs
- Add std.minArray/std.maxArray
Upstream issue: https://github.com/google/jsonnet/pull/1081
Upstream issue: https://github.com/google/jsonnet/pull/1074
=> feat: sync upstream stdlib changes

Cargo.lock, Cargo.toml, cmds/jrsonnet-fmt/Cargo.toml, cmds/jrsonnet-lsp/Cargo.toml, cmds/jrsonnet/Cargo.toml, crates/jrsonnet-cli/Cargo.toml, crates/jrsonnet-evaluator/Cargo.toml, crates/jrsonnet-interner/Cargo.toml, crates/jrsonnet-macros/Cargo.toml, crates/jrsonnet-macros/src/lib.rs, crates/jrsonnet-parser/Cargo.toml, crates/jrsonnet-rowan-parser/Cargo.toml, crates/jrsonnet-stdlib/Cargo.toml, crates/jrsonnet-types/Cargo.toml, xtask/Cargo.toml
This fixes [dependabot#6] reporting vulnerable `rustix` version and moves all dependencies to root `Cargo.toml`.
[dependabot#6]: https://github.com/CertainLach/jrsonnet/security/dependabot/6
=> build(dep): update dependencies and share their versions

Cargo.lock, Cargo.toml, cmds/jrsonnet/Cargo.toml, crates/jrsonnet-cli/Cargo.toml, crates/jrsonnet-evaluator/src/typed/conversions.rs, crates/jrsonnet-stdlib/Cargo.toml, crates/jrsonnet-stdlib/src/lib.rs, crates/jrsonnet-stdlib/src/regex.rs
Upstream issue: https://github.com/google/jsonnet/pull/1039
Excluding questions asked upstream, it should be noted that rust regex crate and re2 syntax are not exactly the same because rust regexes have a bit more features regarding unicode character group matches.
However, there are not enough incompatibilities for writing a regex parser/transpiler closer to the RE2 syntax.
=> feat: add std regex builtins

cmds/jrsonnet/Cargo.toml, crates/jrsonnet-evaluator/src/evaluate/mod.rs
Array comprehension should be able to depend on its own result, and it is able in go-jsonnet/cpp-jsonnet.
Has minimal impact on the performance in the most cases.
Discovered while implementing day 4 of advent of code 2023.
https://github.com/CertainLach/AOC-2023/blob/2ab792288ecfd558473efe2fb3c1eca19f574814/day4.jsonnet#L23
=> fix: lazy object comprehension

crates/jrsonnet-evaluator/src/val.rs, crates/jrsonnet-stdlib/src/arrays.rs
Upstream issue: https://github.com/google/jsonnet/pull/1093
=> feat: allow negative indexes in std.slice

flake.nix
- Building on `x86_64-darwin` seems to work fine, both for jrsonnet package and devShell.
- `package.default` let's you run `nix build .` to build jrsonnet. Same deal when using this flake 
as an input to other ones.
Appreciate all the work!
=> nix: add darwin support and default package

crates/jrsonnet-stdlib/src/lib.rs, crates/jrsonnet-stdlib/src/std.jsonnet, crates/jrsonnet-stdlib/src/strings.rs, tests/golden/builtin_strings.jsonnet, tests/golden/builtin_strings.jsonnet.golden
There are two branches with native implementations of stdlib functions, but none for `std.splitLimirR` yet.
The function needs either two passes over the string (one reverse scan for the nth separator, another to split it starting at this offset) or a temporary array with string slices. The implementation below uses the second, more readable approach.
=> native implementation of std.splitLimitR

.editorconfig, Cargo.lock, Cargo.toml, crates/jrsonnet-evaluator/src/arr/mod.rs, crates/jrsonnet-evaluator/src/val.rs, crates/jrsonnet-stdlib/src/lib.rs, crates/jrsonnet-stdlib/src/std.jsonnet, crates/jrsonnet-stdlib/src/strings.rs, tests/Cargo.toml, tests/golden/builtin_strings_string.jsonnet, tests/golden/builtin_strings_string.jsonnet.golden, tests/tests/golden.rs
This implements builtins for `*stripChars` family of std functions.
=> feat: `*stripChars` builtins
